# DevOps3 Lab1
image: maven:3-jdk-8

stages:
  - build
  - test
  - run

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    #- mvn $MAVEN_CLI_OPTS compile
    - mvn -version
    - java -version
    - mvn -e compile
    

test:
  stage: test
  script:
    # - mvn -e clean verify
    # - mvn test
    - echo "test"

run:
  stage: run
  script:
    #- cd ./gameoflife-build
    - mvn -e install
    #- cd ../gameoflife-core
    - mvn -e install
    - cd ./gameoflife-web/
    - pwd
    - mvn -e jetty:run
    # - mvn package
    #- mvn $MAVEN_CLI_OPTS exec:java -Dexec.mainClass="com.example.app.App"