# DevOps3 Lab1
image: maven:3-jdk-8

stages:
  - build
  - test
  - run

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

#cache:
#  paths:
#    - .m2/repository/
#    - target/

build:
  stage: build
  script:
    #- mvn $MAVEN_CLI_OPTS compile
    #- docker info
    - mvn -version
    - java -version
    - pwd
    - mvn compile
    - mvn clean install

test:
  stage: test
  script:
    # - mvn -e clean verify
    - mvn test
    #- echo "test"

run:
  stage: run
  script:
    #- cd ./gameoflife-build
    #- mvn -e install
    #- cd ../gameoflife-core
    #- mvn install
    #- cd ./gameoflife-web/
    - pwd
    #- mvn -e jetty:run
    - mvn package
    - cd ./gameoflife-web/
    - pwd
    #- mvn clean install
    - mvn package
    - mvn -e jetty:run
    #- mvn $MAVEN_CLI_OPTS exec:java -Dexec.mainClass="com.example.app.App"